### ISSUE TITLE
Add proper tests for div, ldiv, imaxdiv

### ISSUE THREAD

**Issue by phillipjohnston** [embeddedartistry/libc#10]
There are four division functions:

- div
- ldiv
- lldiv
- imaxdiv

Currently, we only have tests that cover lldiv (test/stdlib/lldiv.c). The tests for div are simply a copy of lldiv, and not really testing div(). ldiv and imax div are untested altogether.

To test the other functions, we essentially need to copy the method used to test lldiv.c, but adjust the types and table definitions.

- div needs to have int  type in the table
- ldiv needs to have long type in the table
- imaxdiv needs to have intmax_t type in the table

The values in lldiv can be repurposed to test out imaxdiv, but the suffix of "ull" will need to be changed to "ll" in that file. But new tables of values will need to be generated for div and ldiv.

For div and ldiv, you will need to create a new table that has numbers x, y, and the corresponding div and mod values. Make sure to pick a range of big and small values. The table does not have to be as comprehensive as what exists for lldiv.

**Comment by phillipjohnston** [comment]
There are four division functions:

- div
- ldiv
- lldiv
- imaxdiv

Currently, we only have tests that cover lldiv (test/stdlib/lldiv.c). The tests for div are simply a copy of lldiv, and not really testing div(). ldiv and imax div are untested altogether.

To test the other functions, we essentially need to copy the method used to test lldiv.c, but adjust the types and table definitions.

- div needs to have int  type in the table
- ldiv needs to have long type in the table
- imaxdiv needs to have intmax_t type in the table

The values in lldiv can probably be repurposed to test out imaxdiv. But new tables of values will need to be generated for div and ldiv.

**Comment by AdhamEA** [comment]
Clair Sir
