### ISSUE TITLE
Doxygen documentation: ctype.h

### ISSUE THREAD

**Issue by phillipjohnston** [embeddedartistry/libc#19]
Doxygen support has been added: need to improve the doxygen documentation now.

**Comment by seekaddo** [comment]
@phillipjohnston do you need help with this? If yes please let me know where to start from.

**Comment by phillipjohnston** [comment]
Hey @seekaddo, I do need help with this. I realize this is a vague and broad issue, so I'll create multiple issues covering each header.

An easy one to start with would be [ctype.h](https://github.com/embeddedartistry/libc/blob/master/include/ctype.h). I have documented two functions as an example for you to use. To make things easy, I used the summary from [cppreference](http://en.cppreference.com/w/c/string/byte/isalpha). 

One thing to note is that for this `ctype` implementation, I am only using the default locale currently. So any reference to other locales can be excluded. I have done this for the two example functions.

To build the documentation, you can run `make doc` in the repository root. The documentation can be found at buildresults/doc/html/index.html.

Thank you for your help! Please do not hesitate to reach out if you have any questions.

**Comment by seekaddo** [comment]
@phillipjohnston Thanks for the good introduction and the help guide. I will start right away with it.

**Comment by phillipjohnston** [comment]
Resolved by #29
