### ISSUE TITLE
Feature Request: Add Meson project option to disable (enable?) testing

### ISSUE THREAD

**Issue by fghzxm** [embeddedartistry/libc#192]
CMake provides a built-in variable `LIBC_TESTING_IS_ENABLED` to control whether to generate test targets (which depend on cmocka, which in turn needs to be downloaded). However, Meson doesn't provide an equivalent built-in option, and test targets that are defined are always generated.

I suggest we add a project option `enable-testing` to the Meson project that controls whether test targets are generated (and whether cmocka is downloaded).

(Question: Should this issue be reported to embeddedartistry/meson instead?)

**Comment by phillipjohnston** [comment]
Totally agree this should exist, I'll get something released this week.

**Comment by phillipjohnston** [comment]
Option is `enable-testing`, defaults to `true`.
