### ISSUE TITLE
Doxygen Documentation: memory.h

### ISSUE THREAD

**Issue by phillipjohnston** [embeddedartistry/libc#22]
[include/memory.h](https://github.com/embeddedartistry/libc/blob/master/include/memory.h) needs Doxygen documentation added for each of the functions.

Please see [embeddedartistry/libmemory](https://github.com/embeddedartistry/libmemory) or [include/ctype.h](https://github.com/embeddedartistry/libc/blob/master/include/ctype.h) as a reference for Doxygen function comments.

cppreference.com is a great resource to use for the functional descriptions.

To build the documentation, run `make doc` in the repository root. Documentation output is found at buildresults/doc/html/index.html.

**Comment by seekaddo** [comment]
@phillipjohnston the header file is empty. Do we need to reference the various function or any tipps on this.

**Comment by phillipjohnston** [comment]
I'll take care of this one quickly

**Comment by seekaddo** [comment]
Great
