### ISSUE TITLE
Doxygen Documentation: stddef.h

### ISSUE THREAD

**Issue by phillipjohnston** [embeddedartistry/libc#24]

**Comment by seekaddo** [comment]
@phillipjohnston I will work on this and two others, so that we can atleast close most of the docs for now and move to some more non-trivial stuffs.

**Comment by phillipjohnston** [comment]
Which others?

**Comment by seekaddo** [comment]
This one and `stdlib.h and stdint.h` Are you still working on endians?

**Comment by phillipjohnston** [comment]
I have not had the time to work on it yet. If you would like to knock it out, please feel free. I appreciate your great support.

**Comment by phillipjohnston** [comment]
@seekaddo I've added you as a contributor. Please feel free to assign yourself issues that you are working on.

**Comment by seekaddo** [comment]
@phillipjohnston Thanks. I just activated the 2FA for it.
I am done working on both headers. I will look into the endians when I am done with `stdlib.h`

Question:
Do I now have to use the `embeddedartistry/libc` repos directing for my PRS are I can continue to use my old one? Now I have two on my page now after accepting the invitation.

**Comment by phillipjohnston** [comment]
@seekaddo you can use either one. your preference :)
