### ISSUE TITLE
Doxygen Documentation: string.h

### ISSUE THREAD

**Issue by phillipjohnston** [embeddedartistry/libc#27]
[include/string.h](https://github.com/embeddedartistry/libc/blob/master/include/string.h) needs Doxygen documentation added for each of the functions.

Please see [embeddedartistry/libmemory](https://github.com/embeddedartistry/libmemory) or [include/ctype.h](https://github.com/embeddedartistry/libc/blob/master/include/ctype.h) as a reference for Doxygen function comments.

cppreference.com is a great resource to use for the functional descriptions.

To build the documentation, run `make doc` in the repository root. Documentation output is found at buildresults/doc/html/index.html.

**Comment by seekaddo** [comment]
@phillipjohnston I have already started with the first two functions `memcmp` and `memset`. I will continue with it and also with strings.h

**Comment by phillipjohnston** [comment]
@seekaddo thank you kindly for your help!

**Comment by seekaddo** [comment]
@phillipjohnston You welcome. Thank you for the opportunity.

**Comment by phillipjohnston** [comment]
Fixed by #34
