### ISSUE TITLE
Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by SeanBarber** [embeddedartistry/libc#31]
## Context
Running Safari 11.0.2 on macOS

## Expected Behavior
The Issue Template and Pull Request Template should go to the correct page on Github
## Current Behavior
What is the current behavior?
These links:
[Issue Template/Checklist
Pull Request template/Checklist](https://github.com/embeddedartistry/libc/blob/master/docs/CONTRIBUTING.md#important-resources)
are outdated, leading to a 404 error.

**Comment by SeanBarber** [comment]
I will update these as they are a simple fix requiring the new link.

**Comment by phillipjohnston** [comment]
Thanks for your help!It's quite interesting as I thought the links were well-formed from a Markdown perspective. I made the mistake of using local paths, but forgot the document was stored in the docs folder :)

The CODE_OF_CONDUCT.md link is also broken, could you include that as well?

**Comment by phillipjohnston** [comment]
I will fix other repositories with the same failure
