### ISSUE TITLE
Broken links in the CONTRIBUTING file

### ISSUE THREAD

**Issue by seekaddo** [embeddedartistry/libc#37]
The links to all the test cases files and others are broken.

> Example
> [This](https://github.com/embeddedartistry/libc/blob/master/docs/test) should be changed to [this](https://github.com/embeddedartistry/libc/tree/master/test)
> 
> This [string/string_tests.c](https://github.com/embeddedartistry/libc/blob/master/docs/test/string/string_tests.c) should be [this](https://github.com/embeddedartistry/libc/blob/master/test/string/string_tests.c)
> 
> and the last two`main.c`

**Comment by phillipjohnston** [comment]
Great catch. I moved the guide to the docs folder and missed those link updates.

**Comment by seekaddo** [comment]
Oh ok. Will you revert this or we should just relink everything all over again?

**Comment by phillipjohnston** [comment]
Just fixed :)
