### ISSUE TITLE
Add unit test for strnstr

### ISSUE THREAD

**Issue by phillipjohnston** [embeddedartistry/libc#5]

**Comment by seekaddo** [comment]
I want to start working on some of the test issues. Can you please point me to some good reference or examples. For now I am learning from [this](https://api.cmocka.org/group__cmocka__exec.html#ga7c62fd0acf2235ce98268c28ee262a57)

**Comment by phillipjohnston** [comment]
That website is helpful, and you can also look into the `test` directory in the repository, which has test examples for other functions. Many of the existing tests were imported from an old 'libc-test' repository I found on the web.

I've provided some tips for adding new tests to the CONTRIBUTING guide as well.

I'm not sure what OS you are using, but there may be a linker problem with CMocka - I only have an OSX static library included at the moment. If that's a problem I'll look into a fix.

**Comment by seekaddo** [comment]
@phillipjohnston I have using Max osx sierra and I have install cmocka. Its able to link with my Clion IDE without a problem. I and I have tried a few things here on Travis also. It works well. Take a look [here](https://travis-ci.org/seekaddo/HelloCmocka/jobs/317137051) even on mac osx travis builds ok [here](https://travis-ci.org/seekaddo/HelloCmocka/jobs/317137052). Just with home brew and all was good.

**Comment by seekaddo** [comment]
Thanks for the tipps, I will look into the test examples on CONTRIBUTING guide.

**Comment by seekaddo** [comment]
cmocka is not working when i am trying to build the whole test project. I don't know if is having conflicts with my cmock 1.1 installed on mac osx. But when i build with cmake on my mac as a standalone function it works. I have to figure out a way to build it with the whole project otherwise i can just push it and see the build results from the CI/Jenkins.
