### ISSUE TITLE
make fails with "meson.build:10:0: ERROR: Non-existent build file 'build/compiler/meson.build'"

### ISSUE THREAD

**Issue by James-A-Clark** [embeddedartistry/libc#85]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Project Version/Tag/Comit: master
* Operating System: ubuntu 16.04
* SDK version: n/a
* Toolchain version: n/a

## Expected Behavior

After installing meson and the build dependencies listed in the readme, I expect make to build the product.

## Current Behavior

make gives the following output:
```
 -> make
The Meson build system
Version: 0.50.1
Source dir: /home/jamcla02/workspace/libc
Build dir: /home/jamcla02/workspace/libc/buildresults
Build type: native build
Project name: libc
Project version: undefined
Native C compiler: /opt/gcc/7.3.0/bin/gcc (gcc 7.3.0 "gcc (GCC) 7.3.0")
Native C++ compiler: /opt/gcc/7.3.0/bin/g++ (gcc 7.3.0 "g++ (GCC) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64

meson.build:10:0: ERROR: Non-existent build file 'build/compiler/meson.build'

A full log can be found at /home/jamcla02/workspace/libc/buildresults/meson-logs/meson-log.txt
Makefile:18: recipe for target 'groundwork' failed
make: *** [groundwork] Error 1
```
### Steps to Reproduce

```
git clone https://github.com/embeddedartistry/libc.git
cd libc
sudo apt-get install python3 python3-pip ninja-build
pip3 install --user meson
make
```

[meson-log.txt](https://github.com/embeddedartistry/libc/files/3112609/meson-log.txt)

Thanks!

**Comment by phillipjohnston** [comment]
Hi James,

This project has submodules. You'll need to run `git submodule init` and `git submodule update` to populate them.

I'll add clarifying notes to the README.

**Comment by James-A-Clark** [comment]
Amazing thanks for the quick reply! It's all working now.
