### ISSUE TITLE
Add an ITM putchar implementation

### ISSUE THREAD

**Issue by phillipjohnston** [embeddedartistry/libc#89]
Inspiration:

![Screen Shot 2019-04-03 at 12 13 37](https://user-images.githubusercontent.com/1709063/57183489-86dd2100-6e62-11e9-99ad-d442d765690a.png)

**Comment by salkinium** [comment]
See also https://blog.japaric.io/itm/ for more implementation details (in Rust, but applies to any language).

**Comment by phillipjohnston** [comment]
Thanks!

**Comment by phillipjohnston** [comment]
Closing after @salkinium's feedback:

> It's pretty disappointing tbh. No DMA, no interrupts, no stand-alone functionality, the SWO pin isn't even connected on all Nucleo/Discovery boards, annoying to use via OpenOCD/GDB. Meh.

We'll do this if someone _really_ wants it.
